//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinosPark
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagamentoTipo
    {
        public PagamentoTipo()
        {
            this.Pagamento = new HashSet<Pagamento>();
        }
    
        public byte Id { get; set; }
        public string Descricao { get; set; }
        public bool isAtivo { get; set; }
    
        public virtual ICollection<Pagamento> Pagamento { get; set; }
    }
}
