//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinosPark
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preco
    {
        public short Id { get; set; }
        public System.TimeSpan Tempo { get; set; }
        public decimal Valor { get; set; }
        public bool isMoto { get; set; }
        public bool isAtivo { get; set; }
    }
}
