//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinosPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacionamento
    {
        public Estacionamento()
        {
            this.Evento = new HashSet<Evento>();
        }
    
        public short Id { get; set; }
        public string Nome { get; set; }
        public bool isAtivo { get; set; }
        public Nullable<short> QuantidadeMaxima { get; set; }
    
        public virtual ICollection<Evento> Evento { get; set; }
    }
}
