//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinosPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public Evento()
        {
            this.Pagamento = new HashSet<Pagamento>();
        }
    
        public short Id { get; set; }
        public System.DateTime Entrada { get; set; }
        public Nullable<System.DateTime> Saida { get; set; }
        public string CodigoBarras { get; set; }
        public Nullable<int> VeiculoId { get; set; }
        public Nullable<int> AlunoId { get; set; }
        public short EstacionamentoId { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Estacionamento Estacionamento { get; set; }
        public virtual Veiculo Veiculo { get; set; }
        public virtual ICollection<Pagamento> Pagamento { get; set; }
    }
}
