//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinosPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeiculoModelo
    {
        public VeiculoModelo()
        {
            this.Veiculo = new HashSet<Veiculo>();
        }
    
        public short Id { get; set; }
        public string Descricao { get; set; }
        public Nullable<bool> isAtivo { get; set; }
        public bool isMoto { get; set; }
    
        public virtual ICollection<Veiculo> Veiculo { get; set; }
    }
}
