//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinosPark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        public Veiculo()
        {
            this.Evento = new HashSet<Evento>();
        }
    
        public int Id { get; set; }
        public string Placa { get; set; }
        public string Cor { get; set; }
        public Nullable<short> VeiculoModeloId { get; set; }
        public Nullable<bool> isBloqueado { get; set; }
    
        public virtual ICollection<Evento> Evento { get; set; }
        public virtual VeiculoModelo VeiculoModelo { get; set; }
    }
}
